[[mediatypes]]
= Media types
:code-dir: ../../../src/docs/java/org/springframework/hateoas
:resource-dir: ../../../src/docs/resources/org/springframework/hateoas
:test-dir: ../../../src/test/java/org/springframework/hateoas
:linkattrs:

[[mediatypes.hal]]
== HAL – Hypertext Application Language

https://tools.ietf.org/html/draft-kelly-json-hal-08[JSON Hypertext Application Language] or HAL is one of the simplest
and most widely adopted hypermedia media types adopted when not discussing specific web stacks.

It was the first spec-based media type adopted by Spring HATEAOS.

[[mediatypes.hal.configuration]]
=== Configuring link rendering

In HAL, the `_links` entry is a JSON object. The property names are <<fundamentals.link-relations,link relations>> and
each value is either https://tools.ietf.org/html/draft-kelly-json-hal-07#section-4.1.1[a link object or an array of link objects].

For a given link relation that has two or more links, the spec is clear on representation:

.HAL document with two links associated with one relation
====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/hal/hal-multiple-entry-link-relation.json[]
----
====

But if there is only one link for a given relation, the spec is ambiguous. You could render that as either a single object
or as 1-item array.

By default, Spring HATEOAS uses the most terse approach and renders a single-link relation like this:

.HAL document with single link rendered as an object
====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/hal/hal-single-entry-link-relation-object.json[]
----
====

Some users prefer to not switch between arrays and objects when consuming HAL. They would prefer this type of rendering:

.HAL with single link rendered as an array
====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/hal/hal-single-entry-link-relation-array.json[]
----
====

If you wish to customize this policy, all you have to do is inject a `HalConfiguration` bean into your application configuration.
There are multiple choices.

.Global HAL single-link rendering policy
====
[source, java, indent=0, tabsize=2]
----
include::{code-dir}/SampleAppConfiguration.java[tag=1]
----
<1> Override Spring HATEOAS's default by rendering ALL single-link relations as arrays.
====

If you prefer to only override some particular link relations, you can create a `HalConfiguration`
bean like this:

.Link relation-based HAL single-link rendering policy
====
[source, java, indent=0, tabsize=2]
----
include::{code-dir}/SampleAppConfiguration.java[tag=2]
----
<1> Always render `item` link relations as an array.
<2> Render `prev` link relations as an object when there is only one link.
====

If neither of these match your needs, you can use an Ant-style path patterns:

.Pattern-based HAL single-link rendering policy
====
[source,java,indent=0,tabsize=2]
----
include::{code-dir}/SampleAppConfiguration.java[tag=3]
----
<1> Render all link relations that start with `http` as an array.

NOTE: The pattern-based approach uses Spring's `AntPathMatcher`.
====

All of these `HalConfiguration` withers can be combined to form one comprehensive policy. Be sure to test your API
extensively to avoid surprises.

[[mediatypes.hal.i18n]]
=== Link title internationalization

HAL defines a `title` attribute for its link objects.
These titles can be populated by using Spring's resource bundle abstraction and a resource bundle named `rest-messages` so that clients can use them in their UIs directly.
This bundle will be set up automatically and is used during HAL link serialization.

To define a title for a link, use the key template `_links.$relationName.title` as follows:

.A sample `rest-messages.properties`
====
[source]
----
_links.cancel.title=Cancel order
_links.payment.title=Proceed to checkout
----
====

This will result in the following HAL representation:

.A sample HAL document with link titles defined
====
[source, javascript]
----
{
  "_links" : {
    "cancel" : {
      "href" : "…"
      "title" : "Cancel order"
    },
    "payment" : {
      "href" : "…"
      "title" : "Proceed to checkout"
    }
  }
}
----
====

[[mediatypes.hal.curie-provider]]
=== [[spis.curie-provider]] Using the `CurieProvider` API

The https://tools.ietf.org/html/rfc5988=section-4[Web Linking RFC] describes registered and extension link relation types. Registered rels are well-known strings registered with the https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA registry of link relation types]. Extension `rel` URIs can be used by applications that do not wish to register a relation type. Each one is a URI that uniquely identifies the relation type. The `rel` URI can be serialized as a compact URI or https://www.w3.org/TR/curie[Curie]. For example, a curie of `ex:persons` stands for the link relation type `https://example.com/rels/persons` if `ex` is defined as `https://example.com/rels/{rel}`. If curies are used, the base URI must be present in the response scope.

The `rel` values created by the default `RelProvider` are extension relation types and, as a result, must be URIs, which can cause a lot of overhead. The `CurieProvider` API takes care of that: It lets you define a base URI as a URI template and a prefix that stands for that base URI. If a `CurieProvider` is present, the `RelProvider` prepends all `rel` values with the curie prefix. Furthermore a `curies` link is automatically added to the HAL resource.

The following configuration defines a default curie provider:

====
[source, java]
----
@Configuration
@EnableWebMvc
@EnableHypermediaSupport(type= {HypermediaType.HAL})
public class Config {

  @Bean
  public CurieProvider curieProvider() {
    return new DefaultCurieProvider("ex", new UriTemplate("https://www.example.com/rels/{rel}"));
  }
}
----
====

Note that now the `ex:` prefix automatically appears before all rel values that are not registered with IANA, as in `ex:orders`. Clients can use the `curies` link to resolve a curie to its full form.
The following example shows how to do so:

====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/hal/hal-with-curies.json[]
----
====

Since the purpose of the `CurieProvider` API is to allow for automatic curie creation, you can define only one `CurieProvider` bean per application scope.

[[mediatypes.hal-forms]]
== HAL-FORMS

https://rwcbook.github.io/hal-forms/[HAL-FORMS, window="_blank"] is designed to add runtime FORM support to the <<mediatypes.hal,HAL media type>>.

[quote, Mike Amundsen, HAL-FORMS spec]
____
HAL-FORMS "looks like HAL." However, it is important to keep in mind that HAL-FORMS is not the same as HAL — the two
should not be thought of as interchangeable in any way.
____

To enable this media type, put the following configuration in your code:

.HAL-FORMS enabled application
====
[source, java, tabsize=2]
----
include::{code-dir}/HalFormsApplication.java[tag=code]
----
====

Anytime a client supplies an `Accept` header with `application/prs.hal-forms+json`, you can expect something like this:

.HAL-FORMS sample document
====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/hal/forms/hal-forms-sample.json[]
----
====

Checkout the https://rwcbook.github.io/hal-forms/[HAL-FORMS spec] to understand the details of the *_templates* attribute.
Read about the <<server.affordances,Affordances API>> to augment your controllers with this extra metadata.

As for single-item (`EntityModel`) and aggregate root collections (`CollectionModel`), Spring HATEOAS renders them
identically to <<mediatypes.hal,HAL documents>>.

[[mediatypes.hal-forms.metadata]]
=== Defining HAL-FORMS metadata
HAL-FORMS allows to describe criterias for each form field.
Spring HATEOAS allows to customize those by shaping the model type for the input and output types and using annotations on them.

[options="header", cols="1,4"]
|===============
|Attribute|Description
|`readOnly`| Set to `true` if there's no setter method for the property. If that is present, use Jackson's `@JsonProperty(Access.READ_ONLY)` on the accessors or field explicitly. Not rendered by default, thus defaulting to `false`.
|`regex`| Can be customized by using JSR-303's `@Pattern` annotation either on the field or a type. In case of the latter the pattern will be used for every property declared as that particular type. Not rendered by default.
|`required`| Can be customized by using JSR-303's `@NotNull`. Not rendered by default and thus defaulting to `false`. Templates using `PATCH` as method will automatically have set all properties to not required.
|===============

For types that you cannot annotate manually, you can register a custom pattern via a `HalFormsConfiguration` bean present in the application context.

[source, java]
----
@Configuration
class CustomConfiguration {

  @Bean
  HalFormsConfiguration halFormsConfiguration() {

    HalFormsConfiguration configuration = new HalFormsConfiguration();
    configuration.registerPatternFor(CreditCardNumber.class, "[0-9]{16}");
  }
}
----

This setup will cause the HAL-FORMS template properties for representation model properties of type `CreditCardNumber` to declare a `regex` field with value `[0-9]{16}`.

[[mediatypes.hal-forms.i18n]]
=== Internationalization of form attributes
HAL-FORMS contains attributes that are intended for human interpretation, like a template's title or property prompts.
These can be defined and internationalized using Spring's resource bundle support and the `rest-messages` resource bundle configured by Spring HATEOAS by default.

==== Template titles
To define a template title use the following pattern: `_templates.$affordanceName.title`. Note, that in HAL-FORMS, the name of a template is `default` if it is the only one.
This means that you'll usually have to qualify the key with the local or fully qualified input type name that affordance describes.

.Defining HAL-FORMS template titles
====
[source]
----
_templates.default.title=Some title <1>
_templates.putEmployee.title=Create employee <2>
Employee._templates.default.title=Create employee <3>
com.acme.Employee._templates.default.title=Create employee <4>
----
<1> A global definition for the title using `default` as key.
<2> A global definition for the title using the actual affordance name as key. Unless defined explicitly when creating the affordance, this defaults to `$httpMethod + $simpleInputTypeName`.
<3> A locally defined title to be applied to all types named `Employee`.
<4> A title definition using the fully-qualified type name.
====

NOTE: Keys using the actual affordance name enjoy preference over the defaulted ones.

==== Property prompts
Property prompts can also be resolved via the `rest-messages` resource bundle automatically configured by Spring HATEOAS.
The keys can be defined globally, locally or fully-qualified and need an `._prompt` concatenated to the actual property key:

.Defining prompts for an `email` property
====
[source]
----
firstName._prompt=Firstname <1>
Employee.firstName._prompt=Firstname <2>
com.acme.Employee.firstName._prompt=Firstname <3>
----
<1> All properties named `email` will get "Firstname" rendered, independent of the type they're declared in.
<2> The `firstName` property in types named `Employee` will be prompted "Firstname".
<3> The `firstName` property of `com.acme.Employee` will get a prompt of "Firstname" assigned.
====

A sample document with both template titles and property prompts defined would then look something like this:

.A sample HAL-FORMS document with internationalized template titles and property prompts
====
[source]
----
{
  …,
  "_templates" : {
    "default" : {
      "title" : "Create employee",
      "method" : "put",
      "contentType" : "",
      "properties" : [ {
        "name" : "firstName",
        "prompt" : "Firstname",
        "required" : true
      }, {
        "name" : "lastName",
        "prompt" : "Lastname",
        "required" : true
      }, {
        "name" : "role",
        "prompt" : "Role",
        "required" : true
      } ]
    }
  }
}
----
====

[[mediatypes.collection-json]]
== Collection+JSON

http://amundsen.com/media-types/collection/format/[Collection+JSON, window="_blank"] is a JSON spec registered with IANA-approved media type `application/vnd.collection+json`.

[quote, Mike Amundsen, Collection+JSON spec]
____
http://amundsen.com/media-types/collection/[Collection+JSON, window="_blank"] is a JSON-based read/write hypermedia-type designed to support
management and querying of simple collections.
____

Collection+JSON provides a uniform way to represent both single item resources as well as collections.
To enable this media type, put the following configuration in your code:

.Collection+JSON enabled application
====
[source, java, tabsize=2]
----
include::{code-dir}/CollectionJsonApplication.java[tag=code]
----
====

This configuration will make your application respond to requests that have an `Accept` header of `application/vnd.collection+json`
as shown below.

The following example from the spec shows a single item:

.Collection+JSON single item example
====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/collectionjson/spec-part3.json[]
----
<1> The `self` link is stored in the document's `href` attribute.
<2> The document's top `links` section contains collection-level links (minus the `self` link).
<3> The `items` section contains a collection of data. Since this is a single-item document, it only has one entry.
<4> The `data` section contains actual content. It's made up of properties.
<5> The item's individual `links`.
====

[IMPORTANT]
====
The previous fragment was lifted from the spec. When Spring HATEOAS renders an `EntityModel`, it will:

* Put the `self` link into both the document's `href` attribute and the item-level `href` attribute.
* Put the rest of the model's links into both the top-level `links` as well as the item-level `links`.
* Extract the properties from the `EntityModel` and turn them into
====

When rendering a collection of resources, the document is almost the same, except there will be multiple entries inside
the `items` JSON array, one for each entry.

Spring HATEOAS more specifically will:

* Put the entire collection's `self` link into the top-level `href` attribute.
* The `CollectionModel` links (minus `self`) will be put into the top-level `links`.
* Each item-level `href` will contain the corresponding `self` link for each entry from the `CollectionModel.content` collection.
* Each item-level `links` will contain all other links for each entry from `CollectionModel.content`.


[[mediatypes.uber]]
== UBER - Uniform Basis for Exchanging Representations

https://rawgit.com/uber-hypermedia/specification/master/uber-hypermedia.html[UBER, window="_blank"] is an experimental JSON spec

[quote, Mike Amundsen, UBER spec]
____
The UBER document format is a minimal read/write hypermedia type designed to support simple state transfers and ad-hoc
hypermedia-based transitions.
____

UBER provides a uniform way to represent both single item resources as well as collections. To enable this media type, put the following configuration in your code:

.UBER+JSON enabled application
====
[source, java, tabsize=2]
----
include::{code-dir}/UberApplication.java[tag=code]
----
====

This configuration will make your application respond to requests using the `Accept` header `application/vnd.amundsen-uber+json`
as show below:

.UBER sample document
====
[source, json, tabsize=2]
----
include::{resource-dir}/docs/mediatype/uber/uber-sample.json[]
----
====

This media type is still under development as is the spec itself. Feel free to
https://github.com/spring-projects/spring-hateoas/issues[open a ticket, window="_blank"] if you run into issues using it.

NOTE: *UBER media type* is not associated in any way with *Uber Technologies Inc.*, the ride sharing company.

[[mediatypes.alps]]
== ALPS - Application-Level Profile Semantics

https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-01[ALPS, window="_blank"] is a media type for providing
profile-based metadata about another resource.

[quote, Mike Amundsen, ALPS spec]
____
An ALPS document can be used as a profile to
explain the application semantics of a document with an application-
agnostic media type (such as HTML, HAL, Collection+JSON, Siren,
etc.).  This increases the reusability of profile documents across
media types.
____

ALPS requires no special activation. Instead you "build" an `Alps` record and return it from either a Spring MVC or a Spring WebFlux web method as shown below:

.Building an `Alps` record
====
[source, java, tabsize=2, indent=0]
----
include::{test-dir}/support/WebMvcEmployeeController.java[tag=alps-profile]
----
* This example leverages `PropertyUtils.getExposedProperties()` to extract metadata about the domain object's attributes.
====

This fragment has test data plugged in. It yields JSON like this:

.ALPS JSON
====
----
{
  "version": "1.0",
  "doc": {
    "format": "TEXT",
    "href": "https://example.org/samples/full/doc.html",
    "value": "value goes here"
  },
  "descriptor": [
    {
      "id": "class field [name]",
      "name": "name",
      "type": "SEMANTIC",
      "descriptor": [
        {
          "id": "embedded"
        }
      ],
      "ext": {
        "id": "ext [name]",
        "href": "https://example.org/samples/ext/name",
        "value": "value goes here"
      },
      "rt": "rt for [name]"
    },
    {
      "id": "class field [role]",
      "name": "role",
      "type": "SEMANTIC",
      "descriptor": [
        {
          "id": "embedded"
        }
      ],
      "ext": {
        "id": "ext [role]",
        "href": "https://example.org/samples/ext/role",
        "value": "value goes here"
      },
      "rt": "rt for [role]"
    }
  ]
}
----
====

Instead of linking each field "automatically" to a domain object's fields, you can write them by hand if you like. It's also possible
to use Spring Framework's message bundles and the `MessageSource` interface. This gives you the ability to delegate these values to
locale-specific message bundles and even internationalize the metadata.

[[mediatypes.custom]]
== Registering a custom media type

Spring HATEOAS allows to integrate support for custom media types through a set of SPIs, that third parties can implement.
The building blocks of an such an implementations are:

1. Some form of Jackson ObjectMapper customization. In its most simple case that's a Jackson `Module` implementation.
2. A `LinkDiscoverer` implementation so that the client side support is able to detect links in representations generated.
3. Some configuration infrastructure that will allow Spring HATEOAS to find the custom implementation and pick up its configuration.

[[mediatypes.custom.configuration]]
=== Custom media type configuration

Custom media type implementations are picked up through Spring's `SpringFactories` mechanism, similar to the Java `ServiceLoader` API.
Each media type implementation needs to ship with a `spring.factories` in `META-INF` containing an implementation class entry for the `org.springframework.hateoas.config.MediaTypeConfigurationProvider` key:

.An example `MediaTypeConfigurationProvider` declaration
====
[source]
org.springframework.hateoas.config.MediaTypeConfigurationProvider=\
  com.acme.mymediatype.MyMediaTypeConfigurationProvider
====

That implementation class could then look as follows:

.An example `MediaTypeConfigurationProvider` implementation in `META-INF/spring.factories`
====
[source, java]
----
class MyMediaTypeConfigurationProvider
  implements MediaTypeConfigurationProvider {

  @Override
  public Class<? extends HypermediaMappingInformation> getConfiguration() {
    return MyMediaTypeConfiguration.class; <1>
  }

  @Override
  public boolean supportsAny(Collection<MediaType> mediaTypes) {
    return mediaTypes.contains(MediaTypes.HAL_JSON); <2>
  }
}
----
The configuration class needs to have a default constructor and expose two methods:

<1> A method returning a Spring configuration class that will be included in the application bootstrap when Spring HATEOAS is activated (either implicitly via Spring Boot auto-configuration or via `@EnableHypermediaSupport`).
<2> A callback method that will get the application selected media types to activate passed. This allows the media type implementation to control, when it it will be activated.
====

The configuration class has to implement `HypermediaMappingInformation`. It could look as simple as this:

====
[source, java]
----
@Configuration
class MyMediaTypeConfiguration implements HypermediaMappingInformation {

  @Override
  public List<MediaType> getMediaTypes() {
    return MediaType.parse("application/vnd-acme-media-type") <1>
  }

  @Override
  public Module getJacksonModule() {
    return new Jackson2MediaTypeModule(); <2>
  }

  @Bean
  MyLinkDiscoverer myLinkDiscoverer() {
    return new MyLinkDiscoverer(); <3>
  }
}
----
<1> The configuration class returns the media type it wants to get Spring MVC / Spring WebFlux support set up.
<2> It overrides `getJacksonModule()` to provide custom serializers to create the media type specific representations.
<3> It also declares a custom `LinkDiscoverer` implementation for client side support.
====

The Jackson module usually declares `Serializer` and `Deserializer` implementations for the representation model types `RepresentationModel`, `EntityModel`, `CollectionModel` and `PagedModel`.
In case you need further customization of the Jackson `ObjectMapper` (like a custom `HandlerInstantiator`), you can alternatively override `configureObjectMapper(…)`.

[[mediatypes.custom.recommendation]]
=== Recommendations

The preferred way to implement media type representations is by providing a type hierarchy that matches the expected format and can be serialized by Jackson as is.
In the `Serializer` and `Deserializer` implementations registered for `RepresentationModel`, convert the instances into the media type specific model types and then lookup the Jackson serializer for those.

The media types supported by default use the same configuration mechanism as third party implementations would.
So it's worth studying the implementations in https://github.com/spring-projects/spring-hateoas/tree/master/src/main/java/org/springframework/hateoas/mediatype[the `mediatype` package].
