[[mediatypes]]
= Media types
:code-dir: ../../../src/docs/java/org/springframework/hateoas
:resource-dir: ../../../src/docs/resources/org/springframework/hateoas
:test-dir: ../../../src/test/java/org/springframework/hateoas
:linkattrs:
:tabsize: 2

[[mediatypes.hal]]
== HAL – Hypertext Application Language

https://tools.ietf.org/html/draft-kelly-json-hal-08[JSON Hypertext Application Language] or HAL is one of the simplest
and most widely adopted hypermedia media types adopted when not discussing specific web stacks.

It was the first spec-based media type adopted by Spring HATEOAS.

[[mediatypes.hal.models]]
=== Building HAL representation models

As of Spring HATEOAS 1.1, we ship a dedicated `HalModelBuilder` that allows to create `RepresentationModel` instances through a HAL-idiomatic API.
These are its fundamental assumptions:

1. A HAL representation can be backed by an arbitrary object (an entity) that builds up the domain fields contained in the representation.
2. The representation can be enriched by a variety of embedded documents, which can be either arbitrary objects or HAL representations themselves (i.e. containing nested embeddeds and links).
3. Certain HAL specific patterns (e.g. previews) can be directly used in the API so that the code setting up the representation reads like you'd describe a HAL representation following those idioms.

Here's an example of the API used:

[source, java]
----
// An order
var order = new Order(…); <1>

// The customer who placed the order
var customer = customer.findById(order.getCustomerId());

var customerLink = Link.of("/orders/{id}/customer") <2>
  .expand(order.getId())
  .withRel("customer");

var additional = …

var model = HalModelBuilder.halModel(order)
  .preview(new CustomerSummary(customer)) <3>
  .forLink(customerLink) <4>
  .embed(additional) <5>
  .link(Link.of(…, IanaLinkRelations.SELF));
  .build();
----
<1> We set up some domain type. In this case, an order that has a relationship to the customer that placed it.
<2> We prepare a link pointing to a resource that will expose customer details
<3> We start building a preview by providing the payload that's supposed to be rendered inside the `_embeddable` clause.
<4> We conclude that preview by providing the target link. It transparently gets added to the `_links` object and its link relation is used as the key for the object provided in the previous step.
<5> Other objects can be added to show up under `_embedded`.
The key under which they're listed is derived from the objects relation settings. They're customizable via `@Relation` or a dedicated `LinkRelationProvider` (see <<server.rel-provider>> for details).

[source, javascript]
----
{
  "_links" : {
    "self" : { "href" : "…" }, <1>
    "customer" : { "href" : "/orders/4711/customer" } <2>
  },
  "_embedded" : {
    "customer" : { … }, <3>
    "additional" : { … } <4>
  }
}
----
<1> The `self` link as explicitly provided.
<2> The `customer` link transparently added through `….preview(…).forLink(…)`.
<3> The preview object provided.
<4> Additional elements added via explicit `….embed(…)`.

In HAL `_embedded` is also used to represent top collections.
They're usually grouped under the link relation derived from the object's type.
I.e. a list of orders would look like this in HAL:

[source, javascript]
----
{
  "_embedded" : {
    "orders : [
      … <1>
    ]
  }
}
----
<1> Individual order documents go here.

Creating such a representation is as easy as this:

[source, java]
----
Collection<Order> orders = …;

HalModelBuilder.emptyHalDocument()
  .embed(orders);
----

That said, if the order is empty, there's no way to derive the link relation to appear inside `_embedded`, so that the document will stay empty if the collection is empty.

If you prefer to explicitly communicate an empty collection, a type can be handed into the overload of the `….embed(…)` method taking a `Collection`.
If the collection handed into the method is empty, this will cause a field rendered with its link relation derived from the given type.

[source, java]
----
HalModelBuilder.emptyHalModel()
  .embed(Collections.emptyList(), Order.class);
  // or
  .embed(Collections.emptyList(), LinkRelation.of("orders"));
----

will create the following, more explicit representation.

[source, javascript]
----
{
  "_embedded" : {
    "orders" : []
  }
}
----

[[mediatypes.hal.configuration]]
=== Configuring link rendering

In HAL, the `_links` entry is a JSON object. The property names are <<fundamentals.link-relations,link relations>> and
each value is either https://tools.ietf.org/html/draft-kelly-json-hal-07#section-4.1.1[a link object or an array of link objects].

For a given link relation that has two or more links, the spec is clear on representation:

.HAL document with two links associated with one relation
====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/hal/hal-multiple-entry-link-relation.json[]
----
====

But if there is only one link for a given relation, the spec is ambiguous. You could render that as either a single object
or as a single-item array.

By default, Spring HATEOAS uses the most terse approach and renders a single-link relation like this:

.HAL document with single link rendered as an object
====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/hal/hal-single-entry-link-relation-object.json[]
----
====

Some users prefer to not switch between arrays and objects when consuming HAL. They would prefer this type of rendering:

.HAL with single link rendered as an array
====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/hal/hal-single-entry-link-relation-array.json[]
----
====

If you wish to customize this policy, all you have to do is inject a `HalConfiguration` bean into your application configuration.
There are multiple choices.

.Global HAL single-link rendering policy
====
[source, java, indent=0]
----
include::{code-dir}/SampleAppConfiguration.java[tag=1]
----
<1> Override Spring HATEOAS's default by rendering ALL single-link relations as arrays.
====

If you prefer to only override some particular link relations, you can create a `HalConfiguration`
bean like this:

.Link relation-based HAL single-link rendering policy
====
[source, java, indent=0]
----
include::{code-dir}/SampleAppConfiguration.java[tag=2]
----
<1> Always render `item` link relations as an array.
<2> Render `prev` link relations as an object when there is only one link.
====

If neither of these match your needs, you can use an Ant-style path pattern:

.Pattern-based HAL single-link rendering policy
====
[source,java,indent=0,tabsize=2]
----
include::{code-dir}/SampleAppConfiguration.java[tag=3]
----
<1> Render all link relations that start with `http` as an array.

NOTE: The pattern-based approach uses Spring's `AntPathMatcher`.
====

All of these `HalConfiguration` withers can be combined to form one comprehensive policy. Be sure to test your API
extensively to avoid surprises.

[[mediatypes.hal.i18n]]
=== Link title internationalization

HAL defines a `title` attribute for its link objects.
These titles can be populated by using Spring's resource bundle abstraction and a resource bundle named `rest-messages` so that clients can use them in their UIs directly.
This bundle will be set up automatically and is used during HAL link serialization.

To define a title for a link, use the key template `_links.$relationName.title` as follows:

.A sample `rest-messages.properties`
====
[source]
----
_links.cancel.title=Cancel order
_links.payment.title=Proceed to checkout
----
====

This will result in the following HAL representation:

.A sample HAL document with link titles defined
====
[source, javascript]
----
{
  "_links" : {
    "cancel" : {
      "href" : "…"
      "title" : "Cancel order"
    },
    "payment" : {
      "href" : "…"
      "title" : "Proceed to checkout"
    }
  }
}
----
====

[[mediatypes.hal.curie-provider]]
=== [[spis.curie-provider]] Using the `CurieProvider` API

The https://tools.ietf.org/html/rfc8288#section-2.1[Web Linking RFC] describes registered and extension link relation types. Registered rels are well-known strings registered with the https://www.iana.org/assignments/link-relations/link-relations.xhtml[IANA registry of link relation types]. Extension `rel` URIs can be used by applications that do not wish to register a relation type. Each one is a URI that uniquely identifies the relation type. The `rel` URI can be serialized as a compact URI or https://www.w3.org/TR/curie[Curie]. For example, a curie of `ex:persons` stands for the link relation type `https://example.com/rels/persons` if `ex` is defined as `https://example.com/rels/{rel}`. If curies are used, the base URI must be present in the response scope.

The `rel` values created by the default `RelProvider` are extension relation types and, as a result, must be URIs, which can cause a lot of overhead. The `CurieProvider` API takes care of that: It lets you define a base URI as a URI template and a prefix that stands for that base URI. If a `CurieProvider` is present, the `RelProvider` prepends all `rel` values with the curie prefix. Furthermore a `curies` link is automatically added to the HAL resource.

The following configuration defines a default curie provider:

====
[source, java]
----
@Configuration
@EnableWebMvc
@EnableHypermediaSupport(type= {HypermediaType.HAL})
public class Config {

  @Bean
  public CurieProvider curieProvider() {
    return new DefaultCurieProvider("ex", new UriTemplate("https://www.example.com/rels/{rel}"));
  }
}
----
====

Note that now the `ex:` prefix automatically appears before all rel values that are not registered with IANA, as in `ex:orders`. Clients can use the `curies` link to resolve a curie to its full form.
The following example shows how to do so:

====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/hal/hal-with-curies.json[]
----
====

Since the purpose of the `CurieProvider` API is to allow for automatic curie creation, you can define only one `CurieProvider` bean per application scope.

[[mediatypes.hal-forms]]
== HAL-FORMS

https://rwcbook.github.io/hal-forms/[HAL-FORMS, window="_blank"] is designed to add runtime FORM support to the <<mediatypes.hal,HAL media type>>.

[quote, Mike Amundsen, HAL-FORMS spec]
____
HAL-FORMS "looks like HAL." However, it is important to keep in mind that HAL-FORMS is not the same as HAL — the two
should not be thought of as interchangeable in any way.
____

To enable this media type, put the following configuration in your code:

.HAL-FORMS enabled application
====
[source, java]
----
include::{code-dir}/HalFormsApplication.java[tag=code]
----
====

Anytime a client supplies an `Accept` header with `application/prs.hal-forms+json`, you can expect something like this:

.HAL-FORMS sample document
====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/hal/forms/hal-forms-sample.json[]
----
====

Check out the https://rwcbook.github.io/hal-forms/[HAL-FORMS spec] to understand the details of the *_templates* attribute.
Read about the <<server.affordances,Affordances API>> to augment your controllers with this extra metadata.

As for single-item (`EntityModel`) and aggregate root collections (`CollectionModel`), Spring HATEOAS renders them
identically to <<mediatypes.hal,HAL documents>>.

[[mediatypes.hal-forms.metadata]]
=== Defining HAL-FORMS metadata
HAL-FORMS allows to describe criterias for each form field.
Spring HATEOAS allows to customize those by shaping the model type for the input and output types and using annotations on them.

[options="header", cols="1,4"]
|===============
|Attribute|Description
|`readOnly`| Set to `true` if there's no setter method for the property. If that is present, use Jackson's `@JsonProperty(Access.READ_ONLY)` on the accessors or field explicitly. Not rendered by default, thus defaulting to `false`.
|`regex`| Can be customized by using JSR-303's `@Pattern` annotation either on the field or a type. In case of the latter the pattern will be used for every property declared as that particular type. Not rendered by default.
|`required`| Can be customized by using JSR-303's `@NotNull`. Not rendered by default and thus defaulting to `false`. Templates using `PATCH` as method will automatically have all properties set to not required.
|===============

For types that you cannot annotate manually, you can register a custom pattern via a `HalFormsConfiguration` bean present in the application context.

[source, java]
----
@Configuration
class CustomConfiguration {

  @Bean
  HalFormsConfiguration halFormsConfiguration() {

    HalFormsConfiguration configuration = new HalFormsConfiguration();
    configuration.registerPatternFor(CreditCardNumber.class, "[0-9]{16}");
  }
}
----

This setup will cause the HAL-FORMS template properties for representation model properties of type `CreditCardNumber` to declare a `regex` field with value `[0-9]{16}`.

[[mediatypes.hal-forms.i18n]]
=== Internationalization of form attributes
HAL-FORMS contains attributes that are intended for human interpretation, like a template's title or property prompts.
These can be defined and internationalized using Spring's resource bundle support and the `rest-messages` resource bundle configured by Spring HATEOAS by default.

==== Template titles
To define a template title use the following pattern: `_templates.$affordanceName.title`. Note that in HAL-FORMS, the name of a template is `default` if it is the only one.
This means that you'll usually have to qualify the key with the local or fully qualified input type name that affordance describes.

.Defining HAL-FORMS template titles
====
[source]
----
_templates.default.title=Some title <1>
_templates.putEmployee.title=Create employee <2>
Employee._templates.default.title=Create employee <3>
com.acme.Employee._templates.default.title=Create employee <4>
----
<1> A global definition for the title using `default` as key.
<2> A global definition for the title using the actual affordance name as key. Unless defined explicitly when creating the affordance, this defaults to `$httpMethod + $simpleInputTypeName`.
<3> A locally defined title to be applied to all types named `Employee`.
<4> A title definition using the fully-qualified type name.
====

NOTE: Keys using the actual affordance name enjoy preference over the defaulted ones.

==== Property prompts
Property prompts can also be resolved via the `rest-messages` resource bundle automatically configured by Spring HATEOAS.
The keys can be defined globally, locally or fully-qualified and need an `._prompt` concatenated to the actual property key:

.Defining prompts for an `email` property
====
[source]
----
firstName._prompt=Firstname <1>
Employee.firstName._prompt=Firstname <2>
com.acme.Employee.firstName._prompt=Firstname <3>
----
<1> All properties named `firstName` will get "Firstname" rendered, independent of the type they're declared in.
<2> The `firstName` property in types named `Employee` will be prompted "Firstname".
<3> The `firstName` property of `com.acme.Employee` will get a prompt of "Firstname" assigned.
====

A sample document with both template titles and property prompts defined would then look something like this:

.A sample HAL-FORMS document with internationalized template titles and property prompts
====
[source]
----
{
  …,
  "_templates" : {
    "default" : {
      "title" : "Create employee",
      "method" : "put",
      "contentType" : "",
      "properties" : [ {
        "name" : "firstName",
        "prompt" : "Firstname",
        "required" : true
      }, {
        "name" : "lastName",
        "prompt" : "Lastname",
        "required" : true
      }, {
        "name" : "role",
        "prompt" : "Role",
        "required" : true
      } ]
    }
  }
}
----
====

[[mediatypes.http-problem]]
== HTTP Problem Details

https://tools.ietf.org/html/rfc7807[Problem Details for HTTP APIs] is a media type to carry machine-readable details of errors in a HTTP response to avoid the need to define new error response formats for HTTP APIs.

HTTP Problem Details defines a set of JSON properties that carry additional information to describe error details to HTTP clients.
Find more details about those properties in particular in the relevant section of the https://tools.ietf.org/html/rfc7807#section-3.1[RFC document].

You can create such a JSON response by using the `Problem` media type domain type in your Spring MVC Controller:

.Reporting problem details using Spring HATEOAS' `Problem` type
[source, java]
----
include::{code-dir}/mediatype/problem/PaymentController.java[tags=header;method;footer]
----
<1> You start by creating an instance of `Problem` using the factory methods exposed.
<2> You can define the values for the default properties defined by the media type, e.g. the type URI, the title and details using internationalization features of Spring (see above).
<3> Custom properties can be added via a `Map` or an explicit object (see below).

To use a dedicated object for custom properties, declare a type, create and populate an instance of it and hand this into the `Problem` instance either via `….withProperties(…)` or on instance creation via `Problem.create(…)`.

.Using a dedicated type to capture extended problem properties
[source, java, indent=0]
----
include::{code-dir}/mediatype/problem/PaymentController.java[tags=alternative]
----

This will result in a response looking like this:

.A sample HTTP Problem Details response
[source, java, indent=0]
----
include::{resource-dir}/docs/mediatype/problem/response.json[]
----

[[mediatypes.collection-json]]
== Collection+JSON

http://amundsen.com/media-types/collection/format/[Collection+JSON, window="_blank"] is a JSON spec registered with IANA-approved media type `application/vnd.collection+json`.

[quote, Mike Amundsen, Collection+JSON spec]
____
http://amundsen.com/media-types/collection/[Collection+JSON, window="_blank"] is a JSON-based read/write hypermedia-type designed to support
management and querying of simple collections.
____

Collection+JSON provides a uniform way to represent both single item resources as well as collections.
To enable this media type, put the following configuration in your code:

.Collection+JSON enabled application
====
[source, java]
----
include::{code-dir}/CollectionJsonApplication.java[tag=code]
----
====

This configuration will make your application respond to requests that have an `Accept` header of `application/vnd.collection+json`
as shown below.

The following example from the spec shows a single item:

.Collection+JSON single item example
====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/collectionjson/spec-part3.json[]
----
<1> The `self` link is stored in the document's `href` attribute.
<2> The document's top `links` section contains collection-level links (minus the `self` link).
<3> The `items` section contains a collection of data. Since this is a single-item document, it only has one entry.
<4> The `data` section contains actual content. It's made up of properties.
<5> The item's individual `links`.
====

[IMPORTANT]
====
The previous fragment was lifted from the spec. When Spring HATEOAS renders an `EntityModel`, it will:

* Put the `self` link into both the document's `href` attribute and the item-level `href` attribute.
* Put the rest of the model's links into both the top-level `links` as well as the item-level `links`.
* Extract the properties from the `EntityModel` and turn them into ...
====

When rendering a collection of resources, the document is almost the same, except there will be multiple entries inside
the `items` JSON array, one for each entry.

Spring HATEOAS more specifically will:

* Put the entire collection's `self` link into the top-level `href` attribute.
* The `CollectionModel` links (minus `self`) will be put into the top-level `links`.
* Each item-level `href` will contain the corresponding `self` link for each entry from the `CollectionModel.content` collection.
* Each item-level `links` will contain all other links for each entry from `CollectionModel.content`.


[[mediatypes.uber]]
== UBER - Uniform Basis for Exchanging Representations

https://rawgit.com/uber-hypermedia/specification/master/uber-hypermedia.html[UBER, window="_blank"] is an experimental JSON spec

[quote, Mike Amundsen, UBER spec]
____
The UBER document format is a minimal read/write hypermedia type designed to support simple state transfers and ad-hoc
hypermedia-based transitions.
____

UBER provides a uniform way to represent both single item resources as well as collections. To enable this media type, put the following configuration in your code:

.UBER+JSON enabled application
====
[source, java]
----
include::{code-dir}/UberApplication.java[tag=code]
----
====

This configuration will make your application respond to requests using the `Accept` header `application/vnd.amundsen-uber+json`
as show below:

.UBER sample document
====
[source, javascript]
----
include::{resource-dir}/docs/mediatype/uber/uber-sample.json[]
----
====

This media type is still under development as is the spec itself. Feel free to
https://github.com/spring-projects/spring-hateoas/issues[open a ticket, window="_blank"] if you run into issues using it.

NOTE: *UBER media type* is not associated in any way with *Uber Technologies Inc.*, the ride sharing company.

[[mediatypes.alps]]
== ALPS - Application-Level Profile Semantics

https://tools.ietf.org/html/draft-amundsen-richardson-foster-alps-01[ALPS, window="_blank"] is a media type for providing
profile-based metadata about another resource.

[quote, Mike Amundsen, ALPS spec]
____
An ALPS document can be used as a profile to
explain the application semantics of a document with an application-
agnostic media type (such as HTML, HAL, Collection+JSON, Siren,
etc.).  This increases the reusability of profile documents across
media types.
____

ALPS requires no special activation. Instead you "build" an `Alps` record and return it from either a Spring MVC or a Spring WebFlux web method as shown below:

.Building an `Alps` record
====
[source, java, tabsize=2, indent=0]
----
include::{test-dir}/support/WebMvcEmployeeController.java[tag=alps-profile]
----
* This example leverages `PropertyUtils.getExposedProperties()` to extract metadata about the domain object's attributes.
====

This fragment has test data plugged in. It yields JSON like this:

.ALPS JSON
====
----
{
  "version": "1.0",
  "doc": {
    "format": "TEXT",
    "href": "https://example.org/samples/full/doc.html",
    "value": "value goes here"
  },
  "descriptor": [
    {
      "id": "class field [name]",
      "name": "name",
      "type": "SEMANTIC",
      "descriptor": [
        {
          "id": "embedded"
        }
      ],
      "ext": {
        "id": "ext [name]",
        "href": "https://example.org/samples/ext/name",
        "value": "value goes here"
      },
      "rt": "rt for [name]"
    },
    {
      "id": "class field [role]",
      "name": "role",
      "type": "SEMANTIC",
      "descriptor": [
        {
          "id": "embedded"
        }
      ],
      "ext": {
        "id": "ext [role]",
        "href": "https://example.org/samples/ext/role",
        "value": "value goes here"
      },
      "rt": "rt for [role]"
    }
  ]
}
----
====

Instead of linking each field "automatically" to a domain object's fields, you can write them by hand if you like. It's also possible
to use Spring Framework's message bundles and the `MessageSource` interface. This gives you the ability to delegate these values to
locale-specific message bundles and even internationalize the metadata.

[[mediatypes.community]]
== Community-based media types

Thanks to the <<mediatypes.custom, ability to create your own media type>>, there are several community-led efforts to build additional media types.

[[mediatypes.community.json:api]]
=== JSON:API

* https://jsonapi.org[Specification]
* Media type designation: `application/vnd.api+json`
* Latest Release
** https://toedter.github.io/spring-hateoas-jsonapi/release/reference/index.html[Reference documentation]
** https://toedter.github.io/spring-hateoas-jsonapi/release/api/index.html[API documentation]
* Current Snapshot
** https://toedter.github.io/spring-hateoas-jsonapi/snapshot/reference/index.html[Reference documentation]
** https://toedter.github.io/spring-hateoas-jsonapi/snapshot/api/index.html[API documentation]
* https://github.com/toedter/spring-hateoas-jsonapi[Source]
* Project Lead: https://github.com/toedter[Kai Toedter]

.Maven coordinates
[source,xml,tabsize=2]
----
<dependency>
    <groupId>com.toedter</groupId>
    <artifactId>spring-hateoas-jsonapi</artifactId>
    <version>{see project page for current version}</version>
</dependency>
----

.Gradle coordinates
[source,tabsize=2]
----
implementation 'com.toedter:spring-hateoas-jsonapi:{see project page for current version}'
----

Visit the project page for more details if you want snapshot releases.

[[mediatypes.community.siren]]
=== Siren

* https://github.com/kevinswiber/siren[Specification]
* Media type designation: `application/vnd.siren+json`
* https://spring-hateoas-siren.ingogriebsch.de[Reference documentation]
* https://spring-hateoas-siren.ingogriebsch.de/apidocs[javadocs]
* https://github.com/ingogriebsch/spring-hateoas-siren[Source]
* Project Lead: https://github.com/ingogriebsch[Ingo Griebsch]

.Maven coordinates
[source,xml,tabsize=2]
----
<dependency>
    <groupId>de.ingogriebsch.hateoas</groupId>
    <artifactId>spring-hateoas-siren</artifactId>
    <version>{see project page for current version}</version>
    <scope>compile</scope>
</dependency>
----

.Gradle coordinates
[source,tabsize=2]
----
implementation 'de.ingogriebsch.hateoas:spring-hateoas-siren:{see project page for current version}'
----

[[mediatypes.custom]]
== Registering a custom media type

Spring HATEOAS allows you to integrate custom media types through an SPI.
The building blocks of such an implementation are:

1. Some form of Jackson `ObjectMapper` customization. In its most simple case that's a Jackson `Module` implementation.
2. A `LinkDiscoverer` implementation so that the client-side support is able to detect links in representations.
3. A small bit of infrastructure configuration that will allow Spring HATEOAS to find the custom implementation and pick it up.

[[mediatypes.custom.configuration]]
=== Custom media type configuration

Custom media type implementations are picked up by Spring HATEOAS by scanning the application context for any implementations of the `HypermediaMappingInformation` interface.
Each media type must implement this interface in order to:

* Be applied to <<client.web-client, `WebClient`>>, <<client.web-test-client, `WebTestClient`>>, or <<client.rest-template, `RestTemplate`>> instances.
* Support serving that media type from Spring Web MVC and Spring WebFlux controllers.

To define your own media type could look as simple as this:

====
[source, java]
----
@Configuration
public class MyMediaTypeConfiguration implements HypermediaMappingInformation {

  @Override
  public List<MediaType> getMediaTypes() {
    return MediaType.parse("application/vnd-acme-media-type") <1>
  }

  @Override
  public Module getJacksonModule() {
    return new Jackson2MyMediaTypeModule(); <2>
  }

  @Bean
  MyLinkDiscoverer myLinkDiscoverer() {
    return new MyLinkDiscoverer(); <3>
  }
}
----
<1> The configuration class returns the media type it supports. This applies to both server-side and client-side scenarios.
<2> It overrides `getJacksonModule()` to provide custom serializers to create the media type specific representations.
<3> It also declares a custom `LinkDiscoverer` implementation for further client-side support.
====

The Jackson module usually declares `Serializer` and `Deserializer` implementations for the representation model types `RepresentationModel`, `EntityModel`, `CollectionModel` and `PagedModel`.
In case you need further customization of the Jackson `ObjectMapper` (like a custom `HandlerInstantiator`), you can alternatively override `configureObjectMapper(…)`.

[IMPORTANT]
====
Prior versions of reference documentation has mentioned implementing the `MediaTypeConfigurationProvider` interface and registering it with `spring.factories`.
This is NOT necessary.
This SPI is ONLY used for out-of-the-box media types provided by Spring HATEOAS.
Merely implementing the `HypermediaMappingInformation` interface and registering it as a Spring bean is all that's needed.
====

[[mediatypes.custom.recommendation]]
=== Recommendations

The preferred way to implement media type representations is by providing a type hierarchy that matches the expected format and can be serialized by Jackson as is.
In the `Serializer` and `Deserializer` implementations registered for `RepresentationModel`, convert the instances into the media type-specific model types and then lookup the Jackson serializer for those.

The media types supported by default use the same configuration mechanism as third-party implementations would do.
So it's worth studying the implementations in https://github.com/spring-projects/spring-hateoas/tree/master/src/main/java/org/springframework/hateoas/mediatype[the `mediatype` package].
Note, that the built in media type implementations keep their configuration classes package private, as they're activated via `@EnableHypermediaSupport`.
Custom implementations should probably make those public instead to make sure, users can import those configuration classes from their application packages.

