name: CI Build (Open Source)

on:
  push:
    branches: [ open-source/* ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu22-2-8

    steps:

    - name: Check out sources
      uses: actions/checkout@v6
      with:
        fetch-depth: 100

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: Replace -SNAPSHOT with -INTERNAL-SNAPSHOT in pom.xml
      run: sed -i 's/-SNAPSHOT/-INTERNAL-SNAPSHOT/g' pom.xml

    - name: Build & deploy internal snapshot
      env:
        INTERNAL_REPOSITORY_USERNAME: ${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}
        INTERNAL_REPOSITORY_PASSWORD: ${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}
        INTERNAL_REPOSITORY_URL: ${{ vars.INTERNAL_REPOSITORY_URL }}
      run: ./mvnw -B dependency:list clean deploy -Dsort --settings settings.xml --activate-profiles internal,ci -DaltDeploymentRepository="internal::${{ vars.INTERNAL_REPOSITORY_URL }}"
